
# docker-compose.yml
version: '2'
services:
  app:
    image: node:10.15
    expose:
    - "3000"
    ports:
    - "80:3000"
    env_file:
    - .env
    volumes:
    - .:/app
    - ./node_modules:/app/node_modules:delegated
    working_dir: /app
    command: ['npm', 'run', 'dev']
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
    env_file:
      - .env
